version: '3.8'

services:
  bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: my_little_sniper
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - ../logs:/app/logs
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge